groups:
  menu_chrome:
    background:
      position: [0, 0]
      size: WINDOW
      asset: others/bg
    logo:
      position: [CENTER, 50]
      size: [868, 140]
      asset: others/logo

panels:
  main_menu:
    extends: [menu_chrome]
    objects:
      play:
        position: [CENTER, 250]
        size: [802, 82]
        asset: button/play
        hover: button/play2
      contact:
        position: [CENTER, 350]
        size: [800, 80]
        asset: button/contact_us
        hover: button/contact_us2
      exit:
        position: [CENTER, 450]
        size: [802, 82]
        asset: button/exit
        hover: button/exit2

  contact:
    extends: [menu_chrome]
    objects:
      social_media:
        position: [CENTER, 200]
        size: [600, 600]
        asset: others/social_media
      back:
        position: [70, 700]
        size: [299, 84]
        asset: button/goBack
        hover: button/goBack2

  game:
    objects:
      background:
        position: [ 0, 0 ]
        size: WINDOW
        asset: others/gray_bg
        extension: .jpg

      money_box:
        position: [ 1144, 72 ]   # self.width - 296 = 1440 - 296
        size: [ 300, 125 ]
        asset: others/button

      live_image:
        position: [ 1245, 210 ]
        size: [ 40, 40 ]
        asset: others/heart

      buy_tower_1:
        position: [ 1159, 265 ]
        size: [ 128, 128 ]
        asset: towers/buy_tower1
      buy_tower_2:
        position: [ 1302, 265 ]
        size: [ 128, 128 ]
        asset: towers/buy_tower2
      buy_tower_3:
        position: [ 1159, 455 ]
        size: [ 128, 128 ]
        asset: towers/buy_tower3

      upgrade_planes:
        position: [ 1160, 730 ]
        size: [ 270, 70 ]
        asset: button/upgrade_planes2
        hover: button/upgrade_planes

      menu:
        position: [ 1160, 820 ]
        size: [ 270, 70 ]
        asset: button/menu2
        hover: button/menu