groups:
  menu_chrome:
    logo:
      position: [CENTER, 60]
      size: [1085, 175]
      asset: logo

object_templates:
  btn-sm:
    size: [375, 100]
    asset: btn
    hover: btn_hover
    nine_slice: 10
  btn-lg:
    size: [1000, 100]
    asset: btn
    hover: btn_hover
    nine_slice: 10
  menu_text:
    type: text
    font: Impact
    font_size: 48
  music_toggle:
    position: [ 25, 25 ]
    size: [ 80, 80 ]
    asset: btn_music_pause
    states:
      paused:
        asset: btn_music_resume

panels:
  main_menu:
    extends: [menu_chrome]
    objects:
      play:
        extends: btn-lg
        position: [CENTER, 300]
      contact:
        extends: btn-lg
        position: [CENTER, 420]
      exit:
        extends: btn-lg
        position: [CENTER, 540]

      play_text:
        extends: menu_text
        position: [ CENTER, 320 ]
        text: "PLAY"
      contact_text:
        extends: menu_text
        position: [ CENTER, 440 ]
        text: "CONTACT US"
      exit_text:
        extends: menu_text
        position: [ CENTER, 560 ]
        text: "EXIT"

      music_toggle:
        extends: music_toggle

  contact:
    extends: [menu_chrome]
    objects:
      social_media:
        position: [CENTER, 240]
        size: [750, 750]
        asset: social_media
      back:
        extends: btn-sm
        position: [93, 840]
      back_text:
        extends: menu_text
        position: [235, 860]
        text: "BACK"
      music_toggle:
        extends: music_toggle

  game:
    objects:
      right_panel_bg:
        position: [1500, 0]
        size: [420, 1080]
        color: [50, 50, 50]
      level_text:
        parent: right_panel_bg
        type: text
        position: [CENTER, 2]
        text: "Level 1"
        font: ComicSansMs
        font_size: 50
        color: white
      money_box:
        parent: right_panel_bg
        position: [CENTER, 86]
        size: [375, 156]
        asset: money_box
      money_text:
        parent: right_panel_bg
        type: text
        position: [80, 125]
        text: "0"
        font: ComicSansMs
        font_size: 50
        color: green
      dollar_text:
        parent: right_panel_bg
        type: text
        position: [310, 132]
        text: "$"
        font: ComicSansMs
        font_size: 37
        color: green
      live_image:
        position: [1660, 252]
        size: [50, 50]
        asset: heart
      buy_tower_1:
        position: [1545, 318]
        size: [160, 160]
        asset: buy_tower_1
      buy_tower_2:
        position: [1736, 318]
        size: [160, 160]
        asset: buy_tower_2
      buy_tower_3:
        position: [1545, 546]
        size: [160, 160]
        asset: buy_tower_3
      buy_tower_4:
        position: [1736, 546]
        size: [160, 160]
        asset: buy_tower_4
        states:
          lvl2:
            asset: buy_tower_4_lvl2
      fee_text_bg_1:
        parent: right_panel_bg
        position: [64, 479]
        size: [133, 60]
        asset: money_box
      fee_text_bg_2:
        parent: right_panel_bg
        position: [255, 479]
        size: [133, 60]
        asset: money_box
      fee_text_bg_3:
        parent: right_panel_bg
        position: [64, 707]
        size: [133, 60]
        asset: money_box
      fee_text_bg_4:
        parent: right_panel_bg
        position: [255, 707]
        size: [133, 60]
        asset: money_box
      fee_text_1:
        parent: right_panel_bg
        type: text
        position: [77, 494]
        text: "0 $"
        font: ComicSansMs
        font_size: 25
        color: green
      fee_text_2:
        parent: right_panel_bg
        type: text
        position: [268, 494]
        text: "0 $"
        font: ComicSansMs
        font_size: 25
        color: green
      fee_text_3:
        parent: right_panel_bg
        type: text
        position: [77, 722]
        text: "0 $"
        font: ComicSansMs
        font_size: 25
        color: green
      fee_text_4:
        parent: right_panel_bg
        type: text
        position: [268, 722]
        text: "0 $"
        font: ComicSansMs
        font_size: 25
        color: green
      upgrade_plane_button:
        parent: right_panel_bg
        extends: btn-sm
        position: [CENTER, 876]
        size: [338, 88]
      upgrade_plane_button_text:
        parent: upgrade_plane_button
        extends: menu_text
        position: [CENTER, CENTER]
        text: "UPGRADE PLANES"
      menu_button:
        parent: right_panel_bg
        extends: btn-sm
        position: [CENTER, 984]
        size: [338, 88]
      menu_button_text:
        parent: menu_button
        extends: menu_text
        position: [CENTER, CENTER]
        text: "MENU"
      start_pause_button:
        position: [1640, 780]
        size: [64, 64]
        asset: btn_start
        states:
          pause:
            asset: btn_pause
      x2:
        position: [1747, 780]
        size: [64, 64]
        asset: btn_2x
        states:
          active:
            asset: btn_2x_active